### ISSUE TITLE
Modbus input plugin feature roadmap

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9305]
This issue addresses Telegraf's plans on changes to `inputs.modbus` - all these enhancements will be backwards compatible. The features are listed in priority order with all of the feature requests and workarounds dependent on the plugin code restructuring that will be implemented in Telegraf 1.19. 

Many of the Modbus plugin bugs that have been opened have been due to fact that there is such a wide variety of Modbus devices out there and we cannot test for all of them. We want to understand the issues these array of devices may run into with the Modbus plugin and workarounds for them. Please open a separate [bug report](https://github.com/influxdata/telegraf/issues/new?assignees=&labels=bug&template=Bug_report.md) for any other bugs you may encounter. 

If you would like to test out new Modbus features, please comment on this issue with type of devices you have. 

### Code restructuring
- [x] **Title:          Restructure Modbus plugin**
Description:    Change the plugin code-structure to allow further extensions and ease maintenance
Type:           Code restructuring
Status:         #9141 merged into master
related issues: -
related PRs:    #9141
Target release:	Telegraf 1.19

---- 
### Hardware workarounds
- [x] **Title:          Workaround for closing the connection after every gather cycle**
Description:    Implement workaround for devices with a limited number of simultaneous connections and open/close the connection before/after every gather cycle
Type:           Hardware workaround
Status:         submitted as #9256
related issues: #8225 
related PRs:    #9256
Target release:	Telegraf 1.19+

- [x] **Title:          Workaround for serial connection pause**
Description:    Implement workaround for certain serial connectors requiring a pause between requests
Type:           Hardware workaround
Status:         submitted as #9256 and tested
related issues: #9253
related PRs:    #9256
Target release:	Telegraf 1.19+

- [x] **Title:          Workaround for enforcing bit-register reads from zero**
Description:    Implement workaround for certain devices that can only read bit-registers (coil & discrete) with a zero offset
Type:           Hardware workaround
Status:         workaround exists -- fill all caps and read all coils up to the one you need
related issues: maybe #8905 and #7774?
related PRs:    #12408 
Target release:	Telegraf 1.26.0

----
### Feature requests
- [x] **Title:          Allow reading multiple servers with one connection (gateway)**
Description:    Modbus allows multiple server devices for one client. Allow to read multiple servers with one connection. This is required for devices with constraint connectivity (e.g. max 4 clients or serial devices).
Type:           Feature request
Status:         submitted as #9279, workaround exists -- use multiple instances of the plugin. Will not work with e.g. serial devices.
related issues: #7523, #7066 (closed), #8676 (closed)
related PRs:    #9279 
Target release:	Telegraf 1.21

- [x] **Title:          Allow per-measurement configuration scheme**
Description:    People prefer different views on their modbus topology. One of those views is a per-measurement/metric view. Add a configuration scheme that supports this view.
Type:           Feature request
Status:         -
related issues: -
related PRs:    #13507
Target release:	Telegraf 1.28.

- [x] **Title:          Support Modbus RTU/Ascii over TCP**
Description:    Some (serial-to-ethernet) interfaces require tunneling of RTU/Ascii frames over TCP.
Type:           Feature request
Status:         -
related issues: #7535, #8676?
related PRs:    -
Target release:	Telegraf 1.20+

- [x] **Title:          Allow bool output for bit-register**
Description:    Bit registers are currently output as uint16 zero/one. Allow to also output as bool true/false
Type:           Feature request
Status:         workaround exists -- use converter processors to convert from int to bool
related issues: #9284
related PRs:    #12825 
Target release:	Telegraf 1.26.0

- [ ] **Title:          Support string holding registers**
Description:    Allow reading of character registers and output as string.
Type:           Feature request
Status:         -
related issues: #9062
related PRs:    #14145 
Target release:	Telegraf 1.29.0

_Important Note: Please use client-server instead of master-slave when discussing Modbus features per the Modbus organization: https://www.modbus.org/docs/Client-ServerPR-07-2020-final.docx.pdf_

**Comment by powersj** [comment]
next steps: continue to go through the attached items

**Comment by KE-PaulBright** [comment]
Good Day, Any progress on Support for reading strings? Would love to be able to read the Fault strings on the variety of devices we utilise in our projects. We have an alarm word along with an alarm index (int) coming from our proprietary PLC DFB, but we also have a string available with a more elaborate fault description coming from a VSD Drive for example. This would be awesome for logging faults into influx. If there's any way I can help please let me know.
